name: Generate LLVM snapshots

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *" # end of day everyday

jobs:
  llvm:
    uses: ./.github/workflows/shared.yaml
    secrets: inherit
    with:
      upstream: https://github.com/llvm/llvm-project
      build_script: action_build_llvm.sh
      config: llvm
